### ISSUE TITLE
[TODO] Auto Prep Edit

### ISSUE THREAD

**Issue by angietea101** [angietea101/tali-scripts#7]
**Abstract**
Every edit requires a number of repetitive steps that are needed every time without fail. Make this a one-click button that the user can click before they begin editing.

**Details**
This includes: scaling the upscaled video to the composition size, scene edit detection cuts, adding a watermark, adding coloring, duplicating the main composition layer shying it (make it invisible) and muting the main clip.

**Tasks**
- [ ] Duplicating video
- [x] Mute duplicated video
- [x] Shy original video
- [x] Scaling to composition size
- [x] Scene edit detection
- [x] Add coloring
- [x] Add watermark
